apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployment.app }}
  name: {{ .Values.deployment.name }}
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.deployment.app }}
  type: {{ .Values.service.type }}
