apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: {{ .Values.metadata.labels.name }}
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: {{ .Values.service.type }}
